import { SignJWT, importPKCS8 } from "jose";
import { prisma } from "@/lib/prisma";

// Web Push (RFC 8030) without a third-party library. Uses VAPID
// (RFC 8292) for authentication and *payload-less* pushes — the
// service worker fetches the actual notification body from
// /api/push/latest when the push event fires. This avoids the
// payload-encryption dance (RFC 8291) entirely while still giving the
// user a real OS-level notification.
//
// Required env vars (one-time setup, generated by scripts/gen-vapid.mjs):
//   VAPID_PUBLIC_KEY   — base64url-encoded raw 65-byte P-256 pubkey
//   VAPID_PRIVATE_KEY  — PKCS8 PEM (BEGIN PRIVATE KEY)
//   VAPID_SUBJECT      — mailto: URL or https URL of the site

interface PushPayload {
  kind: string;
  title: string;
  body: string;
  url?: string;
}

const SUBJECT =
  process.env.VAPID_SUBJECT ?? "mailto:hello@indiecomicslive.com";

function vapidEnabled(): boolean {
  return !!(process.env.VAPID_PUBLIC_KEY && process.env.VAPID_PRIVATE_KEY);
}

async function vapidAuthHeader(audience: string): Promise<string> {
  const pem = process.env.VAPID_PRIVATE_KEY!;
  const key = await importPKCS8(pem, "ES256");
  const jwt = await new SignJWT({})
    .setProtectedHeader({ alg: "ES256", typ: "JWT" })
    .setAudience(audience)
    .setSubject(SUBJECT)
    .setExpirationTime(Math.floor(Date.now() / 1000) + 12 * 60 * 60)
    .sign(key);
  return `vapid t=${jwt}, k=${process.env.VAPID_PUBLIC_KEY}`;
}

// Persists the notification + fans it out to every push subscription
// registered for the user. Push delivery is best-effort: failures are
// swallowed (404/410 deletes the dead subscription).
export async function pushToUser(
  userId: string,
  payload: PushPayload,
): Promise<void> {
  await prisma.notification.create({
    data: {
      userId,
      kind: payload.kind,
      title: payload.title,
      body: payload.body,
      url: payload.url ?? null,
    },
  });

  if (!vapidEnabled()) return;

  const subs = await prisma.pushSubscription.findMany({ where: { userId } });
  await Promise.all(
    subs.map(async (s) => {
      try {
        const audience = new URL(s.endpoint).origin;
        const auth = await vapidAuthHeader(audience);
        const r = await fetch(s.endpoint, {
          method: "POST",
          headers: {
            Authorization: auth,
            TTL: "3600",
            "Content-Length": "0",
            Urgency: "normal",
          },
        });
        if (r.status === 404 || r.status === 410) {
          await prisma.pushSubscription
            .delete({ where: { id: s.id } })
            .catch(() => {});
        }
      } catch (err) {
        console.warn("[push] dispatch failed", { id: s.id, err });
      }
    }),
  );
}
